# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digits < Formula
  desc "Agent-native telephony CLI — manage phone numbers, SMS, and calls"
  homepage "https://github.com/ivan-burazin/digits"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.0/digits_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "3ff1c352688ce3334b8bf7a5128bb886f0c95810e167ff5a0218e707355ca141"

      define_method(:install) do
        bin.install "digits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.0/digits_0.1.0_Darwin_arm64.tar.gz"
      sha256 "2890626c934d39f4d3ccf3419838b3184bc7b6bab431bb9ab3597edf1c2db247"

      define_method(:install) do
        bin.install "digits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.0/digits_0.1.0_Linux_x86_64.tar.gz"
      sha256 "e729a4c2e9d0f4135f08549cb106ad346d1cb7940946c071ce86d3599139ec32"
      define_method(:install) do
        bin.install "digits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.0/digits_0.1.0_Linux_arm64.tar.gz"
      sha256 "054fe4ad0268f5de5713d6b05e2ef465ede37e1ea9aff535e3e112ce9c73d9c2"
      define_method(:install) do
        bin.install "digits"
      end
    end
  end

  test do
    system "#{bin}/digits", "--help"
  end
end
