# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digits < Formula
  desc "Agent-native telephony CLI — manage phone numbers, SMS, and calls"
  homepage "https://github.com/ivan-burazin/digits"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.3/digits_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "2a9c926395c57e4ee1cf3404271b3bf551e4747a4b3564e13dde4050b6a23d9d"

      define_method(:install) do
        bin.install "digits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.3/digits_0.1.3_Darwin_arm64.tar.gz"
      sha256 "167efcaafba3f1f3555c743027a7619a5b6f2bb80d61e756091f14fefc3605cc"

      define_method(:install) do
        bin.install "digits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.3/digits_0.1.3_Linux_x86_64.tar.gz"
      sha256 "ce81781621010cba820c7d47373c647cb1a50d1e9fdad0d1eb2971a89233b99f"
      define_method(:install) do
        bin.install "digits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivan-burazin/digits-cli/releases/download/v0.1.3/digits_0.1.3_Linux_arm64.tar.gz"
      sha256 "1ce3d25da8c28eabbbc2458d50b571ed10854a34990f8e90f0b264110b12c7b8"
      define_method(:install) do
        bin.install "digits"
      end
    end
  end

  test do
    system "#{bin}/digits", "--help"
  end
end
